### ISSUE TITLE
Runtime package.json check causes breakage when bundled

### ISSUE THREAD

**Issue by sidvishnoi** [googleapis/nodejs-logging#1361]
If `@google-cloud/logging-min` or `@google-cloud/logging` is bundled (say, via esbuild), it crashes at runtime as the instrumentation code wants to access `package.json`.

https://github.com/googleapis/nodejs-logging/blob/90bb09f1cc736c2930db3e6513637f448cf8d22b/src/utils/instrumentation.ts#L189-L199

[`getNodejsLibraryVersion`](https://github.com/googleapis/nodejs-logging/blob/90bb09f1cc736c2930db3e6513637f448cf8d22b/src/utils/instrumentation.ts#L189-L199) should be inlined during build-step.

#### Environment details

  - OS: Linux / Google Cloud Functions
  - Node.js version: 16
  - npm version: 8.4.1
  - `@google-cloud/logging` version: 10.2.0

#### Steps to reproduce

  1. `await log.write(entry)`
  1. Bundle with esbuild (CommonJS)

```
Error: Cannot find module '/package.json'
Require stack:
- /workspace/index.js
- /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/loader.js
- /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getNodejsLibraryVersion (/node_modules/.pnpm/@google-cloud+logging-min@10.2.0/node_modules/@google-cloud/logging-min/src/utils/instrumentation.ts:193:20)
    at createDiagnosticEntry (/node_modules/.pnpm/@google-cloud+logging-min@10.2.0/node_modules/@google-cloud/logging-min/src/utils/instrumentation.ts:115:31)
    at populateInstrumentationInfo (/node_modules/.pnpm/@google-cloud+logging-min@10.2.0/node_modules/@google-cloud/logging-min/src/utils/instrumentation.ts:87:18)
    at Log.write (/node_modules/.pnpm/@google-cloud+logging-min@10.2.0/node_modules/@google-cloud/logging-min/src/log.ts:980:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at logger2 (/lib/logging-gcloud.js:44:12)
```

**Comment by losalex** [comment]
Thanks @sidvishnoi for opening this issue - I prepared a fix for this just to eliminate a crash and will work later on more appropriate solution.

**Comment by losalex** [comment]
@sidvishnoi , the fix is submitted - will release it
