### ISSUE TITLE
Logs not appearing without explicit resource specified

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-logging#396]
I discovered issue [@google-cloud/logging-winston#262](https://github.com/googleapis/nodejs-logging-winston/issues/262) where one has to explicitly set a `resource` when configuring a `LoggingWinston` instance to have logs correctly appear in Stackdriver Logging.

The configuration, though, is just passed to `@google-cloud/logging`.  Thus, the underlying issue, I think, should be addressed in this repo instead, and I am closing issue [@google-cloud/logging-winston#262](https://github.com/googleapis/nodejs-logging-winston/issues/262).

**Comment by stephenplusplus** [comment]
Sorry that I'm a bit unclear on the issue-- is it that an error is thrown when a resource isn't specified, or is the log entry being misplaced, referring to this line from the other issue?

> [...] the logs appear under the `global` category when running the app locally, but still under the `GAE Application` section when running the app on AppEngine.

**Comment by DominicKramer** [comment]
Consider the following code:
```js
import * as winston from 'winston';
import {LoggingWinston} from '@google-cloud/logging-winston';

const logger = winston.createLogger({
  level: 'info',
  transports: [
    new LoggingWinston({
      projectId: 'some-project'
    })
  ]
});
logger.info('some message');
```
When the `logger.info` line is invoked, the following error is thrown:
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: 3 INVALID_ARGUMENT: A monitored resource must be specified for each log entry
    at Object.exports.createStatusError (/home/dominicdkramer/Temp/winston-log-limit/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/dominicdkramer/Temp/winston-log-limit/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/dominicdkramer/Temp/winston-log-limit/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/dominicdkramer/Temp/winston-log-limit/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/dominicdkramer/Temp/winston-log-limit/node_modules/grpc/src/client_interceptors.js:845:24)
Emitted 'error' event at:
    at DerivedLogger.transportEvent (/home/dominicdkramer/Temp/winston-log-limit/node_modules/winston/lib/winston/logger.js:625:12)
    at LoggingWinston.emit (events.js:194:15)
    at onwriteError (/home/dominicdkramer/Temp/winston-log-limit/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/home/dominicdkramer/Temp/winston-log-limit/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at Immediate.WritableState.onwrite (/home/dominicdkramer/Temp/winston-log-limit/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
Changing 
```js
new LoggingWinston({
  projectId: 'some-project'
})
```
to
```js
new LoggingWinston({
  projectId: 'some-project',
  resource: {
    type: 'global'
  }
})
```
causes the error to disappear and the logs correctly appear (in this case under the `global` section in the Stackderiver Logs Viewer).

**Comment by stephenplusplus** [comment]
Is it possible to try this again? While working on [this PR](https://github.com/googleapis/nodejs-logging/pull/424), I noticed if an error happens when we try to fetch metadata from the various GC* endpoints, we would end up not setting a default resource. But now we do.

**Comment by DominicKramer** [comment]
I've tried with the newest logging-winston that uses an updated `@google-cloud/logging` and it looks like the default resource is being set now.
