### ISSUE TITLE
There are race conditions with system tests

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-logging#401]
It looks like there's some problem with grpc-js here. 

https://source.cloud.google.com/results/invocations/46b0629a-2095-4ecd-b06a-19faf2a9b286/targets/cloud-devrel%2Fclient-libraries%2Fnodejs%2Fpresubmit%2Fgoogleapis%2Fnodejs-logging%2Fnode8%2Fsystem-test-grpcjs/log

```
  Logging
    1) "before all" hook
(node:184) UnhandledPromiseRejectionWarning: Error: Not available in this library. Use @grpc/proto-loader and loadPackageDefinition instead
    at Object.exports.loadObject (/tmpfs/src/github/nodejs-logging/node_modules/@grpc/grpc-js/build/src/index.js:103:11)
    at GrpcClient.loadProto (/tmpfs/src/github/nodejs-logging/node_modules/@google-cloud/pubsub/node_modules/google-gax/src/grpc.ts:198:30)
    at new PublisherClient (/tmpfs/src/github/nodejs-logging/node_modules/@google-cloud/pubsub/build/src/v1/publisher_client.js:95:15)
    at PubSub.getClient_ (/tmpfs/src/github/nodejs-logging/node_modules/@google-cloud/pubsub/build/src/index.js:614:25)
    at auth.getProjectId (/tmpfs/src/github/nodejs-logging/node_modules/@google-cloud/pubsub/build/src/index.js:607:22)
    at getProjectIdAsync.then.r (/tmpfs/src/github/nodejs-logging/node_modules/google-auth-library/build/src/auth/googleauth.js:74:48)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    2) "after all" hook
```

**Comment by alexander-fenster** [comment]
This happens in pubsub which is bundled with an old Gax that does not know how to deal with our new environment variable. To fix:

1. Update gax dependency in pubsub and release pubsub
2. Update pubsub devDependency in `package.json`: 
https://github.com/googleapis/nodejs-logging/blob/4f0dd8a6d801f6abf1921d244fc65319ffe6d8ff/package.json#L79

**Comment by JustinBeckwith** [comment]
Thanks for the investigation!

**Comment by JustinBeckwith** [comment]
Pretty sure this was fixed :)
