### ISSUE TITLE
Error: Attempt to write logs with no transports

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-logging#427]
_From @dorshay6 on October 11, 2018 13:31_

When sending a large log (body of the requestor sql query) I get the following error and there is no way to limit log size from Winston.

```
[winston] Attempt to write logs with no transports {“message”:“Thu, 11 Oct 2018 13:04:32 GMT uncaughtException: 3 INVALID_ARGUMENT: Log entry with size 318.8K exceeds maximum size of 110.0K, stack: Error: 3 INVALID_ARGUMENT: Log entry with size 318.8K exceeds maximum size of 110.0K\n    at Object.exports.createStatusError (/usr/src/app/node_modules/grpc/src/common.js:87:15)\n    at Object.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:1188:28)\n    at InterceptingListener._callNext (/usr/src/app/node_modules/grpc/src/client_interceptors.js:564:42)\n    at InterceptingListener.onReceiveStatus (/usr/src/app/node_modules/grpc/src/client_interceptors.js:614:8)\n    at callback (/usr/src/app/node_modules/grpc/src/client_interceptors.js:841:24)“,”level”:“error”}
```

#### Environment details

  - OS: Docker (node:8.9.4)
  - Node.js version: 8.9.4
  - npm version:
  - `@google-cloud/logging-winston` version: 0.10.2

#### Steps to reproduce

  1. Send a log with over 110k size

_Copied from original issue: googleapis/nodejs-logging-winston#190_

**Comment by DominicKramer** [comment]
_From @dinvlad on October 18, 2018 16:52_

Same issue here! It would be nice to be able either truncate log messages, or better still, automatically split them into multiple entries. As it stands right now, we miss critical messages completely. We can limit that manually I think, but that's not as convenient.

**Comment by DominicKramer** [comment]
Thank you for letting us know about this and for suggesting solutions.  It is really valuable feedback.  I'll keep this thread updated with updates on how we address this.

**Comment by DominicKramer** [comment]
_From @kyle-mccarthy on January 26, 2019 3:59_

I am having this issue after winston emits an error event.  The specific error is a "TCP Read failed" and may be related to https://github.com/googleapis/google-cloud-node/issues/2438

**Comment by DominicKramer** [comment]
The issue is that it is the size of the log entry itself and not just the message that cannot be over 110K.  This makes it difficult to split the log entry into multiple multiple entries if it is the labels and not just the log message that makes the log entry too large.

Truncating messages and labels would be an easier approach.  Another approach would be to truncate labels but split the message into multiple entries (with each entry having duplicate labels).

I'm going to investigate whether these approaches are feasible.

**Comment by DominicKramer** [comment]
_From @dinvlad on March 11, 2019 0:3_

I’d say that splitting messages into multiple lines would be the first and easier way to solve the problem (I’d even guess this covers the majority of setups).

**Comment by DominicKramer** [comment]
I've moved this issue to the nodejs-logging repo since this issue should be handled by the `@google-cloud/logging` module itself that `@google-cloud/logging-winston` and `@google-cloud/logging-bunyan` use.
