### ISSUE TITLE
upgraded to 5.3.1 but still get FetchError

### ISSUE THREAD

**Issue by robymes** [googleapis/nodejs-logging#587]
Hello, even if I tried to upgrade to latest 5.3.1 version, I still get the FetchError when sending log entries to Stackdriver

#### Environment details

  - OS: Windows 10
  - Node.js version: 10.16.3
  - npm version: 6.9.0
  - `@google-cloud/logging` version: 5.3.1
 - `@google-cloud/logging-winston` version: 2.0.1

package.json
```javascript
{
    "name": "ei.logging.gcp",
    "description": "Node.js app for ei.logging.gcp",
    "version": "0.1.0",
    "author": "Roberto Messora <roberto.messora@jakala.com>",
    "dependencies": {
        "body-parser": "1.19.0",
        "cors": "2.8.5",
        "dotenv": "8.1.0",
        "express": "4.17.1",
        "kafka-node": "4.1.3",
        "swaggerize-express": "4.0.5",
        "swagmock": "1.0.0",
        "uuid": "3.3.3",
        "winston": "3.2.1",
        "@google-cloud/logging": "5.3.1",
        "@google-cloud/logging-winston": "2.0.1",
        "@google-cloud/bigquery": "4.2.1"
    },
    "main": "server.js",
    "devDependencies": {
        "eslint": "6.4.0"
    }
}
```

#### Steps to reproduce

Powershell in VS Code
  1. rm node_modules/
  2. rm package-lock.json
  3. npm --save install
  4. npm rebuild

I tried both winston logging and direct logging, but I got the same result:
```
(node:6028) UnhandledPromiseRejectionWarning: FetchError: request to http://169.254.169.254/computeMetadata/v1/instance failed, reason: connect ENETUNREACH 169.254.169.254:80
    at ClientRequest.<anonymous> (d:\Docs\Lavoro\ValueLab\LocalSearch\RfP Data Platform\Test\NodeJs\src2\ei.logging.gcp\node_modules\node-fetch\lib\index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:6028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Debugger listening on ws://127.0.0.1:47129/36775233-d024-4a79-a9af-8609b5a8e477
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2019-09-19T20:57:15.400Z [winstonConsoleLogger] info: Kafka consumer ready
2019-09-19T20:57:16.124Z [winstonConsoleLogger] info: Kafka producer ready
(node:6028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by robymes** [comment]
Hello
any news on this?
I'm still getting the same error, if using the latest version

**Comment by bcoe** [comment]
@robymes could you provide the output from `npm ls`, in the folder the application that is having problems?

**Comment by robymes** [comment]
This is the risult

```
+-- @google-cloud/bigquery@4.2.1
| +-- @google-cloud/common@2.2.2
| | +-- @google-cloud/projectify@1.0.1 deduped
| | +-- @google-cloud/promisify@1.0.2 deduped
| | +-- arrify@2.0.1 deduped
| | +-- duplexify@3.7.1
| | | +-- end-of-stream@1.4.4 deduped
| | | +-- inherits@2.0.4 deduped
| | | +-- readable-stream@2.3.6 deduped
| | | `-- stream-shift@1.0.0 deduped
| | +-- ent@2.2.0
| | +-- extend@3.0.2 deduped
| | +-- google-auth-library@5.2.2 deduped
| | +-- retry-request@4.1.1
| | | +-- debug@4.1.1
| | | | `-- ms@2.1.2 deduped
| | | `-- through2@3.0.1 deduped
| | `-- teeny-request@5.2.1 deduped
| +-- @google-cloud/paginator@2.0.1
| | +-- arrify@2.0.1 deduped
| | `-- extend@3.0.2 deduped
| +-- @google-cloud/promisify@1.0.2
| +-- arrify@2.0.1
| +-- big.js@5.2.2
| +-- duplexify@4.1.1
| | +-- end-of-stream@1.4.4
| | | `-- once@1.4.0
| | |   `-- wrappy@1.0.2
| | +-- inherits@2.0.4
| | +-- readable-stream@3.4.0
| | | +-- inherits@2.0.4 deduped
| | | +-- string_decoder@1.1.1 deduped
| | | `-- util-deprecate@1.0.2 deduped
| | `-- stream-shift@1.0.0
| +-- extend@3.0.2
| +-- is@3.3.0
| +-- stream-events@1.0.5
| | `-- stubs@3.0.0
| +-- string-format-obj@1.1.1
| `-- uuid@3.3.3 deduped
+-- @google-cloud/logging@5.3.1
| +-- @google-cloud/common-grpc@1.0.5
| | +-- @google-cloud/common@2.2.2 deduped
| | +-- @google-cloud/projectify@1.0.1 deduped
| | +-- @google-cloud/promisify@1.0.2 deduped
| | +-- @grpc/grpc-js@0.5.4
| | | `-- semver@6.3.0 deduped
| | +-- @grpc/proto-loader@0.5.2
| | | +-- lodash.camelcase@4.3.0
| | | `-- protobufjs@6.8.8 deduped
| | +-- duplexify@4.1.1 deduped
| | +-- extend@3.0.2 deduped
| | +-- is@3.3.0 deduped
| | +-- retry-request@4.1.1 deduped
| | `-- teeny-request@5.2.1 deduped
| +-- @google-cloud/paginator@2.0.1 deduped
| +-- @google-cloud/projectify@1.0.1
| +-- @google-cloud/promisify@1.0.2 deduped
| +-- @opencensus/propagation-stackdriver@0.0.17
| | +-- @opencensus/core@0.0.17
| | | +-- continuation-local-storage@3.2.1
| | | | +-- async-listener@0.6.10
| | | | | +-- semver@5.7.1
| | | | | `-- shimmer@1.2.1 deduped
| | | | `-- emitter-listener@1.1.2
| | | |   `-- shimmer@1.2.1 deduped
| | | +-- log-driver@1.2.7
| | | +-- semver@6.3.0 deduped
| | | +-- shimmer@1.2.1
| | | `-- uuid@3.3.3 deduped
| | +-- hex2dec@1.1.2
| | `-- uuid@3.3.3 deduped
| +-- arrify@2.0.1 deduped
| +-- eventid@0.1.2
| | +-- d64@1.0.0
| | `-- uuid@3.3.3 deduped
| +-- extend@3.0.2 deduped
| +-- gcp-metadata@3.0.0
| | +-- gaxios@2.0.1
| | | +-- abort-controller@3.0.0 deduped
| | | +-- extend@3.0.2 deduped
| | | +-- https-proxy-agent@2.2.2 deduped
| | | `-- node-fetch@2.6.0 deduped
| | `-- json-bigint@0.3.0
| |   `-- bignumber.js@7.2.1
| +-- google-auth-library@5.2.2
| | +-- arrify@2.0.1 deduped
| | +-- base64-js@1.3.1
| | +-- fast-text-encoding@1.0.0
| | +-- gaxios@2.0.1 deduped
| | +-- gcp-metadata@3.0.0 deduped
| | +-- gtoken@4.1.0
| | | +-- gaxios@2.0.1 deduped
| | | +-- google-p12-pem@2.0.2
| | | | `-- node-forge@0.9.0
| | | +-- jws@3.2.2 deduped
| | | `-- mime@2.4.4
| | +-- jws@3.2.2
| | | +-- jwa@1.4.1
| | | | +-- buffer-equal-constant-time@1.0.1
| | | | +-- ecdsa-sig-formatter@1.0.11
| | | | | `-- safe-buffer@5.1.2 deduped
| | | | `-- safe-buffer@5.1.2 deduped
| | | `-- safe-buffer@5.1.2 deduped
| | `-- lru-cache@5.1.1
| |   `-- yallist@3.0.3
| +-- google-gax@1.6.1
| | +-- @grpc/grpc-js@0.5.4 deduped
| | +-- @grpc/proto-loader@0.5.2 deduped
| | +-- abort-controller@3.0.0
| | | `-- event-target-shim@5.0.1
| | +-- duplexify@3.7.1
| | | +-- end-of-stream@1.4.4 deduped
| | | +-- inherits@2.0.4 deduped
| | | +-- readable-stream@2.3.6 deduped
| | | `-- stream-shift@1.0.0 deduped
| | +-- google-auth-library@5.2.2 deduped
| | +-- is-stream-ended@0.1.4
| | +-- lodash.at@4.6.0
| | +-- lodash.has@4.5.2
| | +-- node-fetch@2.6.0
| | +-- protobufjs@6.8.8 deduped
| | +-- retry-request@4.1.1 deduped
| | +-- semver@6.3.0 deduped
| | `-- walkdir@0.4.1
| +-- is@3.3.0 deduped
| +-- on-finished@2.3.0
| | `-- ee-first@1.1.1
| +-- protobufjs@6.8.8
| | +-- @protobufjs/aspromise@1.1.2
| | +-- @protobufjs/base64@1.1.2
| | +-- @protobufjs/codegen@2.0.4
| | +-- @protobufjs/eventemitter@1.1.0
| | +-- @protobufjs/fetch@1.1.0
| | | +-- @protobufjs/aspromise@1.1.2 deduped
| | | `-- @protobufjs/inquire@1.1.0 deduped
| | +-- @protobufjs/float@1.0.2
| | +-- @protobufjs/inquire@1.1.0
| | +-- @protobufjs/path@1.1.2
| | +-- @protobufjs/pool@1.1.0
| | +-- @protobufjs/utf8@1.1.0
| | +-- @types/long@4.0.0
| | +-- @types/node@10.14.19
| | `-- long@4.0.0
| +-- pumpify@2.0.0
| | +-- duplexify@4.1.1 deduped
| | +-- inherits@2.0.4 deduped
| | `-- pump@3.0.0
| |   +-- end-of-stream@1.4.4 deduped
| |   `-- once@1.4.0 deduped
| +-- snakecase-keys@3.1.0
| | +-- map-obj@4.1.0
| | `-- to-snake-case@1.0.0
| |   `-- to-space-case@1.0.0
| |     `-- to-no-case@1.0.2
| +-- stream-events@1.0.5 deduped
| +-- teeny-request@5.2.1
| | +-- http-proxy-agent@2.1.0
| | | +-- agent-base@4.3.0
| | | | `-- es6-promisify@5.0.0
| | | |   `-- es6-promise@4.2.8 deduped
| | | `-- debug@3.1.0
| | |   `-- ms@2.0.0
| | +-- https-proxy-agent@2.2.2
| | | +-- agent-base@4.3.0 deduped
| | | `-- debug@3.2.6 deduped
| | +-- node-fetch@2.6.0 deduped
| | +-- stream-events@1.0.5 deduped
| | `-- uuid@3.3.3 deduped
| +-- through2@3.0.1
| | `-- readable-stream@2.3.6
| |   +-- core-util-is@1.0.2 deduped
| |   +-- inherits@2.0.4 deduped
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@2.0.1
| |   +-- safe-buffer@5.1.2 deduped
| |   +-- string_decoder@1.1.1 deduped
| |   `-- util-deprecate@1.0.2 deduped
| `-- type-fest@0.8.1
+-- @google-cloud/logging-winston@2.0.1
| +-- @google-cloud/logging@5.3.1 deduped
| +-- google-auth-library@5.2.2 deduped
| +-- lodash.mapvalues@4.6.0
| +-- logform@2.1.2
| | +-- colors@1.4.0
| | +-- fast-safe-stringify@2.0.7
| | +-- fecha@2.3.3
| | +-- ms@2.1.2
| | `-- triple-beam@1.3.0 deduped
| +-- triple-beam@1.3.0
| `-- winston-transport@4.3.0
|   +-- readable-stream@2.3.6 deduped
|   `-- triple-beam@1.3.0 deduped
+-- body-parser@1.19.0
| +-- bytes@3.1.0
| +-- content-type@1.0.4
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- depd@1.1.2
| +-- http-errors@1.7.2
| | +-- depd@1.1.2 deduped
| | +-- inherits@2.0.3
| | +-- setprototypeof@1.1.1 deduped
| | +-- statuses@1.5.0 deduped
| | `-- toidentifier@1.0.0
| +-- iconv-lite@0.4.24
| | `-- safer-buffer@2.1.2
| +-- on-finished@2.3.0 deduped
| +-- qs@6.7.0
| +-- raw-body@2.4.0
| | +-- bytes@3.1.0 deduped
| | +-- http-errors@1.7.2 deduped
| | +-- iconv-lite@0.4.24 deduped
| | `-- unpipe@1.0.0
| `-- type-is@1.6.18
|   +-- media-typer@0.3.0
|   `-- mime-types@2.1.24
|     `-- mime-db@1.40.0
+-- cors@2.8.5
| +-- object-assign@4.1.1
| `-- vary@1.1.2
+-- dotenv@8.1.0
+-- eslint@6.4.0
| +-- @babel/code-frame@7.5.5
| | `-- @babel/highlight@7.5.0
| |   +-- chalk@2.4.2 deduped
| |   +-- esutils@2.0.3 deduped
| |   `-- js-tokens@4.0.0
| +-- ajv@6.10.2
| | +-- fast-deep-equal@2.0.1
| | +-- fast-json-stable-stringify@2.0.0
| | +-- json-schema-traverse@0.4.1
| | `-- uri-js@4.2.2
| |   `-- punycode@2.1.1
| +-- chalk@2.4.2
| | +-- ansi-styles@3.2.1
| | | `-- color-convert@1.9.3
| | |   `-- color-name@1.1.3
| | +-- escape-string-regexp@1.0.5
| | `-- supports-color@5.5.0
| |   `-- has-flag@3.0.0
| +-- cross-spawn@6.0.5
| | +-- nice-try@1.0.5
| | +-- path-key@2.0.1
| | +-- semver@5.7.1
| | +-- shebang-command@1.2.0
| | | `-- shebang-regex@1.0.0
| | `-- which@1.3.1
| |   `-- isexe@2.0.0
| +-- debug@4.1.1
| | `-- ms@2.1.2 deduped
| +-- doctrine@3.0.0
| | `-- esutils@2.0.3 deduped
| +-- eslint-scope@5.0.0
| | +-- esrecurse@4.2.1
| | | `-- estraverse@4.3.0 deduped
| | `-- estraverse@4.3.0
| +-- eslint-utils@1.4.2
| | `-- eslint-visitor-keys@1.1.0 deduped
| +-- eslint-visitor-keys@1.1.0
| +-- espree@6.1.1
| | +-- acorn@7.1.0
| | +-- acorn-jsx@5.0.2
| | `-- eslint-visitor-keys@1.1.0 deduped
| +-- esquery@1.0.1
| | `-- estraverse@4.3.0 deduped
| +-- esutils@2.0.3
| +-- file-entry-cache@5.0.1
| | `-- flat-cache@2.0.1
| |   +-- flatted@2.0.1
| |   +-- rimraf@2.6.3
| |   | `-- glob@7.1.4
| |   |   +-- fs.realpath@1.0.0
| |   |   +-- inflight@1.0.6
| |   |   | +-- once@1.4.0 deduped
| |   |   | `-- wrappy@1.0.2 deduped
| |   |   +-- inherits@2.0.4 deduped
| |   |   +-- minimatch@3.0.4 deduped
| |   |   +-- once@1.4.0 deduped
| |   |   `-- path-is-absolute@1.0.1
| |   `-- write@1.0.3
| |     `-- mkdirp@0.5.1 deduped
| +-- functional-red-black-tree@1.0.1
| +-- glob-parent@5.1.0
| | `-- is-glob@4.0.1 deduped
| +-- globals@11.12.0
| +-- ignore@4.0.6
| +-- import-fresh@3.1.0
| | +-- parent-module@1.0.1
| | | `-- callsites@3.1.0
| | `-- resolve-from@4.0.0
| +-- imurmurhash@0.1.4
| +-- inquirer@6.5.2
| | +-- ansi-escapes@3.2.0
| | +-- chalk@2.4.2 deduped
| | +-- cli-cursor@2.1.0
| | | `-- restore-cursor@2.0.0
| | |   +-- onetime@2.0.1
| | |   | `-- mimic-fn@1.2.0
| | |   `-- signal-exit@3.0.2
| | +-- cli-width@2.2.0
| | +-- external-editor@3.1.0
| | | +-- chardet@0.7.0
| | | +-- iconv-lite@0.4.24 deduped
| | | `-- tmp@0.0.33
| | |   `-- os-tmpdir@1.0.2
| | +-- figures@2.0.0
| | | `-- escape-string-regexp@1.0.5 deduped
| | +-- lodash@4.17.15 deduped
| | +-- mute-stream@0.0.7
| | +-- run-async@2.3.0
| | | `-- is-promise@2.1.0
| | +-- rxjs@6.5.3
| | | `-- tslib@1.10.0
| | +-- string-width@2.1.1
| | | +-- is-fullwidth-code-point@2.0.0
| | | `-- strip-ansi@4.0.0
| | |   `-- ansi-regex@3.0.0
| | +-- strip-ansi@5.2.0
| | | `-- ansi-regex@4.1.0
| | `-- through@2.3.8
| +-- is-glob@4.0.1
| | `-- is-extglob@2.1.1
| +-- js-yaml@3.13.1
| | +-- argparse@1.0.10
| | | `-- sprintf-js@1.0.3
| | `-- esprima@4.0.1
| +-- json-stable-stringify-without-jsonify@1.0.1
| +-- levn@0.3.0
| | +-- prelude-ls@1.1.2
| | `-- type-check@0.3.2
| |   `-- prelude-ls@1.1.2 deduped
| +-- lodash@4.17.15
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- natural-compare@1.4.0
| +-- optionator@0.8.2
| | +-- deep-is@0.1.3
| | +-- fast-levenshtein@2.0.6
| | +-- levn@0.3.0 deduped
| | +-- prelude-ls@1.1.2 deduped
| | +-- type-check@0.3.2 deduped
| | `-- wordwrap@1.0.0
| +-- progress@2.0.3
| +-- regexpp@2.0.1
| +-- semver@6.3.0
| +-- strip-ansi@5.2.0
| | `-- ansi-regex@4.1.0
| +-- strip-json-comments@3.0.1
| +-- table@5.4.6
| | +-- ajv@6.10.2 deduped
| | +-- lodash@4.17.15 deduped
| | +-- slice-ansi@2.1.0
| | | +-- ansi-styles@3.2.1 deduped
| | | +-- astral-regex@1.0.0
| | | `-- is-fullwidth-code-point@2.0.0
| | `-- string-width@3.1.0
| |   +-- emoji-regex@7.0.3
| |   +-- is-fullwidth-code-point@2.0.0
| |   `-- strip-ansi@5.2.0
| |     `-- ansi-regex@4.1.0
| +-- text-table@0.2.0
| `-- v8-compile-cache@2.1.0
+-- express@4.17.1
| +-- accepts@1.3.7
| | +-- mime-types@2.1.24 deduped
| | `-- negotiator@0.6.2
| +-- array-flatten@1.1.1
| +-- body-parser@1.19.0 deduped
| +-- content-disposition@0.5.3
| | `-- safe-buffer@5.1.2 deduped
| +-- content-type@1.0.4 deduped
| +-- cookie@0.4.0
| +-- cookie-signature@1.0.6
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- depd@1.1.2 deduped
| +-- encodeurl@1.0.2
| +-- escape-html@1.0.3
| +-- etag@1.8.1
| +-- finalhandler@1.1.2
| | +-- debug@2.6.9
| | | `-- ms@2.0.0
| | +-- encodeurl@1.0.2 deduped
| | +-- escape-html@1.0.3 deduped
| | +-- on-finished@2.3.0 deduped
| | +-- parseurl@1.3.3 deduped
| | +-- statuses@1.5.0 deduped
| | `-- unpipe@1.0.0 deduped
| +-- fresh@0.5.2
| +-- merge-descriptors@1.0.1
| +-- methods@1.1.2
| +-- on-finished@2.3.0 deduped
| +-- parseurl@1.3.3
| +-- path-to-regexp@0.1.7
| +-- proxy-addr@2.0.5
| | +-- forwarded@0.1.2
| | `-- ipaddr.js@1.9.0
| +-- qs@6.7.0 deduped
| +-- range-parser@1.2.1
| +-- safe-buffer@5.1.2
| +-- send@0.17.1
| | +-- debug@2.6.9
| | | `-- ms@2.0.0
| | +-- depd@1.1.2 deduped
| | +-- destroy@1.0.4
| | +-- encodeurl@1.0.2 deduped
| | +-- escape-html@1.0.3 deduped
| | +-- etag@1.8.1 deduped
| | +-- fresh@0.5.2 deduped
| | +-- http-errors@1.7.2 deduped
| | +-- mime@1.6.0
| | +-- ms@2.1.1
| | +-- on-finished@2.3.0 deduped
| | +-- range-parser@1.2.1 deduped
| | `-- statuses@1.5.0 deduped
| +-- serve-static@1.14.1
| | +-- encodeurl@1.0.2 deduped
| | +-- escape-html@1.0.3 deduped
| | +-- parseurl@1.3.3 deduped
| | `-- send@0.17.1 deduped
| +-- setprototypeof@1.1.1
| +-- statuses@1.5.0
| +-- type-is@1.6.18 deduped
| +-- utils-merge@1.0.1
| `-- vary@1.1.2 deduped
+-- kafka-node@4.1.3
| +-- async@2.6.3
| | `-- lodash@4.17.15 deduped
| +-- binary@0.3.0
| | +-- buffers@0.1.1
| | `-- chainsaw@0.1.0
| |   `-- traverse@0.3.9
| +-- bl@2.2.0
| | +-- readable-stream@2.3.6 deduped
| | `-- safe-buffer@5.1.2 deduped
| +-- buffer-crc32@0.2.13
| +-- buffermaker@1.2.1
| | `-- long@1.1.2
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- denque@1.4.1
| +-- lodash@4.17.15 deduped
| +-- minimatch@3.0.4 deduped
| +-- nested-error-stacks@2.1.0
| +-- optional@0.1.4
| +-- retry@0.10.1
| +-- snappy@6.2.3
| | +-- bindings@1.5.0
| | | `-- file-uri-to-path@1.0.0
| | +-- nan@2.14.0
| | `-- prebuild-install@5.3.2
| |   +-- detect-libc@1.0.3
| |   +-- expand-template@2.0.3
| |   +-- github-from-package@0.0.0
| |   +-- minimist@1.2.0
| |   +-- mkdirp@0.5.1 deduped
| |   +-- napi-build-utils@1.0.1
| |   +-- node-abi@2.11.0
| |   | `-- semver@5.7.1
| |   +-- noop-logger@0.1.1
| |   +-- npmlog@4.1.2
| |   | +-- are-we-there-yet@1.1.5
| |   | | +-- delegates@1.0.0
| |   | | `-- readable-stream@2.3.6 deduped
| |   | +-- console-control-strings@1.1.0
| |   | +-- gauge@2.7.4
| |   | | +-- aproba@1.2.0
| |   | | +-- console-control-strings@1.1.0 deduped
| |   | | +-- has-unicode@2.0.1
| |   | | +-- object-assign@4.1.1 deduped
| |   | | +-- signal-exit@3.0.2 deduped
| |   | | +-- string-width@1.0.2
| |   | | | +-- code-point-at@1.1.0
| |   | | | +-- is-fullwidth-code-point@1.0.0
| |   | | | | `-- number-is-nan@1.0.1
| |   | | | `-- strip-ansi@3.0.1 deduped
| |   | | +-- strip-ansi@3.0.1
| |   | | | `-- ansi-regex@2.1.1
| |   | | `-- wide-align@1.1.3
| |   | |   `-- string-width@1.0.2 deduped
| |   | `-- set-blocking@2.0.0
| |   +-- pump@3.0.0 deduped
| |   +-- rc@1.2.8
| |   | +-- deep-extend@0.6.0
| |   | +-- ini@1.3.5
| |   | +-- minimist@1.2.0 deduped
| |   | `-- strip-json-comments@2.0.1
| |   +-- simple-get@3.1.0
| |   | +-- decompress-response@4.2.1
| |   | | `-- mimic-response@2.0.0
| |   | +-- once@1.4.0 deduped
| |   | `-- simple-concat@1.0.0
| |   +-- tar-fs@2.0.0
| |   | +-- chownr@1.1.3
| |   | +-- mkdirp@0.5.1 deduped
| |   | +-- pump@3.0.0 deduped
| |   | `-- tar-stream@2.1.0
| |   |   +-- bl@3.0.0
| |   |   | `-- readable-stream@3.4.0 deduped
| |   |   +-- end-of-stream@1.4.4 deduped
| |   |   +-- fs-constants@1.0.0
| |   |   +-- inherits@2.0.4 deduped
| |   |   `-- readable-stream@3.4.0
| |   |     +-- inherits@2.0.4 deduped
| |   |     +-- string_decoder@1.1.1 deduped
| |   |     `-- util-deprecate@1.0.2 deduped
| |   +-- tunnel-agent@0.6.0
| |   | `-- safe-buffer@5.1.2 deduped
| |   `-- which-pm-runs@1.0.0
| `-- uuid@3.3.3 deduped
+-- swaggerize-express@4.0.5
| +-- async@0.9.2
| +-- caller@0.0.1
| | `-- tape@2.3.3
| |   +-- deep-equal@0.1.2
| |   +-- defined@0.0.0
| |   +-- inherits@2.0.4 deduped
| |   +-- jsonify@0.0.0
| |   +-- resumer@0.0.0
| |   | `-- through@2.3.8 deduped
| |   `-- through@2.3.8 deduped
| +-- core-util-is@1.0.2
| +-- debuglog@1.0.1
| +-- js-yaml@3.13.1 deduped
| `-- swaggerize-routes@1.0.11
|   +-- caller@1.0.1
|   +-- core-util-is@1.0.2 deduped
|   +-- debuglog@1.0.1 deduped
|   +-- enjoi@1.0.4
|   | +-- core-util-is@1.0.2 deduped
|   | `-- joi@6.10.1
|   |   +-- hoek@2.16.3
|   |   +-- isemail@1.2.0
|   |   +-- moment@2.24.0 deduped
|   |   `-- topo@1.1.0
|   |     `-- hoek@2.16.3 deduped
|   `-- swagger-schema-official@2.0.0-bab6bed
+-- swagmock@1.0.0
| +-- call-me-maybe@1.0.1
| +-- chance@1.1.0
| +-- moment@2.24.0
| +-- randexp@0.4.9
| | +-- drange@1.1.1
| | `-- ret@0.2.2
| `-- swagger-parser@3.4.2
|   +-- call-me-maybe@1.0.1 deduped
|   +-- debug@3.2.6
|   | `-- ms@2.1.2 deduped
|   +-- es6-promise@4.2.8
|   +-- json-schema-ref-parser@1.4.1
|   | +-- call-me-maybe@1.0.1 deduped
|   | +-- debug@2.6.9
|   | | `-- ms@2.0.0
|   | +-- es6-promise@3.3.1
|   | +-- js-yaml@3.13.1 deduped
|   | `-- ono@2.2.5
|   +-- ono@4.0.11
|   | `-- format-util@1.0.3
|   +-- swagger-methods@1.0.8
|   +-- swagger-schema-official@2.0.0-bab6bed deduped
|   `-- z-schema@3.25.1
|     +-- commander@2.20.0
|     +-- core-js@2.6.9
|     +-- lodash.get@4.4.2
|     +-- lodash.isequal@4.5.0
|     `-- validator@10.11.0
+-- uuid@3.3.3
`-- winston@3.2.1
  +-- async@2.6.3 deduped
  +-- diagnostics@1.1.1
  | +-- colorspace@1.1.2
  | | +-- color@3.0.0
  | | | +-- color-convert@1.9.3 deduped
  | | | `-- color-string@1.5.3
  | | |   +-- color-name@1.1.3 deduped
  | | |   `-- simple-swizzle@0.2.2
  | | |     `-- is-arrayish@0.3.2
  | | `-- text-hex@1.0.0
  | +-- enabled@1.0.2
  | | `-- env-variable@0.0.5
  | `-- kuler@1.0.1
  |   `-- colornames@1.1.1
  +-- is-stream@1.1.0
  +-- logform@2.1.2 deduped
  +-- one-time@0.0.4
  +-- readable-stream@3.4.0
  | +-- inherits@2.0.4 deduped
  | +-- string_decoder@1.1.1
  | | `-- safe-buffer@5.1.2 deduped
  | `-- util-deprecate@1.0.2
  +-- stack-trace@0.0.10
  +-- triple-beam@1.3.0 deduped
  `-- winston-transport@4.3.0 deduped
```

**Comment by bcoe** [comment]
@robymes thank you, this is helpful; I think I might actually have an idea. We check for the error codes ` (err.code === 'ENOTFOUND' || err.code === 'ENOENT')`, but not `ENETUNREACH`. 

I'm wondering if this error is only cropping up on Windows, when using the IP rather than the DNS. I'll push a patch tomorrow and we can see if it fixes things.

**Comment by robymes** [comment]
Hello @bcoe 
do you have any update on this?
I'm currently using an older Winston Logging version that actually works, but I would prefer to use the latest one or just use Stackdriver logging without Winston.

**Comment by bcoe** [comment]
:wave: hey @robymes sorry for the slow reply, I've been traveling for the past two weeks. I'll make an effort to get an updated version out the door checking for the additional error code first thing next week (sorry it's taken a bit longer than I indicated).

**Comment by robymes** [comment]
Hi @bcoe
Thank you for the support

**Comment by clintjansen** [comment]
Have the same issue with @google-cloud/logging-winston
Also on windows, tried all versions and 0.11.1 is the only one without the FetchError.
Thanks for looking into it!

**Comment by bcoe** [comment]
@robymes @clintjansen, if you delete your `node_modules`, and remove `package-lock.json`, this issue is hopefully addressed in the latest version of `gcp-metadata`. Let me know if this fixes your problems and I'll close this issue?

**Comment by robymes** [comment]
issue resolved thanks @bcoe !
removed everything and then reinstalled with npm, now works fine, both with and without Winston

**Comment by bcoe** [comment]
@robymes awesome, let me know if you bump into any more issues in the future.
