### ISSUE TITLE
Exception during Logger instantiation in v5.3.0-v5.3.1

### ISSUE THREAD

**Issue by koldoon** [googleapis/nodejs-logging#592]
Since 5.3.0 version it is impossible to instantiate the Logging -  application throws an exception:

```___/node_modules/protobufjs/src/root.js:192
    for (var i = 0, resolved; i < filename.length; ++i)
                                          ^
                                          TypeError: Cannot read property 'length' of undefined
                                          
at Root.load (___/node_modules/protobufjs/src/root.js:192:44)
at Root.loadSync (___/node_modules/protobufjs/src/root.js:235:17)
at Object.loadSync (___/node_modules/@grpc/proto-loader/build/src/index.js:230:27)
at GrpcClient.loadFromProto (___/node_modules/google-gax/build/src/grpc.js:118:44)
at GrpcClient.loadProto (___/node_modules/google-gax/build/src/grpc.js:145:21)
at new ConfigServiceV2Client (___/node_modules/@google-cloud/logging/build/src/v2/config_service_v2_client.js:121:28)
at new Logging (___/node_modules/@google-cloud/logging/build/src/index.js:142:30)    
```

this is because the **filename** variable can also be **undefined** because in config_service_v2_client.js
in here:
```
    const protos = gaxGrpc.loadProto(
      opts.fallback ? require('../../protos/protos.json') : nodejsProtoPath
    );
```
gaxGrpc.loadProto() method is called with just a single parameter.

**Comment by koldoon** [comment]
Seems, the problem is in old google-gax dependency.

**Comment by stephenplusplus** [comment]
@koldoon I tried with 5.3.0 and couldn't reproduce. Could you share the code as well as an `npm ls`? It might not hurt to try a fresh `rm -rf node_modules && npm install` as well.
