### ISSUE TITLE
System tests are flaky

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-logging#702]
The change in https://github.com/googleapis/nodejs-logging/pull/701 shouldn't have any effect on the system tests.

**Comment by stephenplusplus** [comment]
Example output:

```
1) Logging
       "after all" hook in "Logging":
     Error: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
      at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:30:26)
      at Http2CallStream.call.on (node_modules/@grpc/grpc-js/build/src/client.js:96:33)
      at process.nextTick (node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)
      at process._tickCallback (internal/process/next_tick.js:61:11)



Deleting 64 test logs
Deleting nodejs-logging-system-test-1581247995403-5d0816ce2ebd failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248017048-2f98d67f08da failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248057995-0174f0064990 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248079280-6f50d7b92899 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248139973-4bb213f41468 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248160258-6ecf672dad59 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248160382-459cce82aa8c failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248161200-bf5b31705d61 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581248161990-13beab2b2021 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581327086493-029040be726c failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581327127854-98235013e2f0 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
Deleting nodejs-logging-system-test-1581327168610-9db8a41fc038 failed: 8 RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Control requests' and limit 'Control requests per minute' of service 'logging.googleapis.com' for consumer 'project_number:1046198160504'.
```

**Comment by bcoe** [comment]
@stephenplusplus if there's no quick fix, let's just revert to the old approach we were using for deleting logs.

It sounds like you had a relatively quick modification you could make however?

**Comment by stephenplusplus** [comment]
Yeah, I will have a PR soon and if it doesn't produce satisfactory results, we can just rollback to the old style in the meantime.

**Comment by stephenplusplus** [comment]
PR: #703
