### ISSUE TITLE
Installing from Docker

### ISSUE THREAD

**Issue by sergiuds** [googleapis/nodejs-logging#747]
Hey guys,
I am using @google-cloud/logging-bunyan(^2.0.3) which relies on your package(^7.0.0)  and I have an issue when I try to install and run from Docker (tried with node v10 and node v12.13)
```
Error: Cannot find module 'protobufjs/minimal'
Require stack:
- /myapppath/node_modules/@google-cloud/logging/build/protos/protos.js
- /myapppath/node_modules/@google-cloud/logging/build/src/index.js
- /myapppath/node_modules/@google-cloud/logging-bunyan/build/src/middleware/express.js
- /myapppath/node_modules/@google-cloud/logging-bunyan/build/src/index.js
- /myapppath/node_modules/@dandsltd/k8s-logging/bunyan_logger_provider.js
- /myapppath/node_modules/@dandsltd/k8s-logging/index.js
- /myapppath/routes/dispatch/dispatch.js
- /myapppath/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /myapppath/node_modules/@google-cloud/logging/build/protos/protos.js:22:34
    at Object.<anonymous> (/myapppath/node_modules/@google-cloud/logging/build/protos/protos.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/myapppath/node_modules/@google-cloud/logging/build/src/index.js:1052:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/myapppath/node_modules/@google-cloud/logging/build/protos/protos.js',
    '/myapppath/node_modules/@google-cloud/logging/build/src/index.js',
    '/myapppath/node_modules/@google-cloud/logging-bunyan/build/src/middleware/express.js',
    '/myapppath/node_modules/@google-cloud/logging-bunyan/build/src/index.js',
    '/myapppath/node_modules/@dandsltd/k8s-logging/bunyan_logger_provider.js',
    '/myapppath/node_modules/@dandsltd/k8s-logging/index.js',
    '/myapppath/routes/dispatch/dispatch.js',
    '/myapppath/app.js'
  ]
}
```

**Comment by sergiuds** [comment]
it worked well until 2-3 days ago

**Comment by sergiuds** [comment]
Ignore it. I had a peer dependency issue
