### ISSUE TITLE
Error with webpack: "error reading first path in the walk .../protos"

### ISSUE THREAD

**Issue by slhck** [googleapis/nodejs-logging#859]
#### Environment details

  - OS: macOS/Linux
  - Node.js version: 14.3.0
  - npm version: 6.14.5
  - `@google-cloud/logging` version: 7.3.0 and 8.0.1

#### Steps to reproduce

1. Clone the following repo: https://github.com/slhck/pino-stackdriver/
1. Checkout the branch `git checkout update`
1. Run `yarn install && yarn run build && node dist/index.js`

#### Error Description

The program errors with:

```
➜ node dist/index.js
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: error reading first path in the walk /Users/werner/Documents/Projects/slhck/protos
Error: ENOENT: no such file or directory, lstat '/Users/werner/Documents/Projects/slhck/protos'
    at EventEmitter.<anonymous> (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:242:92015)
    at Object.onceWrapper (events.js:422:26)
    at EventEmitter.emit (events.js:315:20)
    at i (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:242:90731)
    at w (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:242:90829)
    at a (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:242:92081)
    at Function.a.sync (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:242:92438)
    at Object.<anonymous> (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:26:178743)
    at r (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:1:110)
    at Object.<anonymous> (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:3:95373)
Emitted 'error' event at:
    at EventEmitter.<anonymous> (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:242:92002)
    at Object.onceWrapper (events.js:422:26)
    [... lines matching original stack trace ...]
    at Object.<anonymous> (/Users/werner/Documents/Projects/slhck/google-sdk-error/dist/index.js:3:95373)
```

**Comment by slhck** [comment]
The program is using `pino-stackdriver` which loads `@google-cloud/logging`. The `update` branch is using the latest version of the latter package, so it's not `pino-stackdriver` that is the issue.

**Comment by slhck** [comment]
It seems this can be fixed by setting:

```
    node: {
      __dirname: true,
    }
```

in the webpack config.

**Comment by slhck** [comment]
Reopening, as even that does not solve the issue. Depending on where I run the packed file from, I still get the error:

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: error reading first path in the walk node_modules/google-gax/protos
Error: ENOENT: no such file or directory, lstat 'node_modules/google-gax/protos'
```

It tries to find a `node_modules` directory that isn't there at runtime.

**Comment by alexander-fenster** [comment]
@slhck Have you tried using the webpack config similar to the one we publish (https://github.com/googleapis/nodejs-logging/blob/master/webpack.config.js), and passing `{fallback: true}` to the logging client constructor?

**Comment by slhck** [comment]
@alexander-fenster I tried with the fallback option and the following webpack config, but I get this error:

```
ERROR in ./node_modules/@grpc/grpc-js/package.json
Module parse failed: Unexpected end of JSON input while parsing near ''
File was processed with these loaders:
 * ./node_modules/null-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
SyntaxError: Unexpected end of JSON input while parsing near ''
    at JSON.parse (<anonymous>)
    at parseJson (./node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (./node_modules/webpack/lib/JsonParser.js:16:16)
    at ./node_modules/webpack/lib/NormalModule.js:482:32
    at ./node_modules/webpack/lib/NormalModule.js:358:12
    at ./node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (./node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (./node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at ./node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (./node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (./node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at ./node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at ./node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
 @ ./node_modules/google-gax/build/src/grpc.js 71:31-68
 @ ./node_modules/google-gax/build/src/index.js
 @ ./node_modules/@google-cloud/logging/build/src/index.js
 @ ./node_modules/pino-stackdriver/src/stackdriver.js
 @ ./node_modules/pino-stackdriver/src/index.js
 @ ./src/Logger.ts
 @ ./src/index.ts
```

Config:

```
module.exports = {
  entry: './src/index.ts',
  target: 'node',
  mode: 'production',
  node: {
    __dirname: false,
    child_process: 'empty',
    fs: 'empty',
    crypto: 'empty',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
        options: {
          // disable type checker - we will use it in fork plugin
          transpileOnly: true,
        },
      },
      {
        test: /node_modules[\\/]@grpc[\\/]grpc-js/,
        use: 'null-loader',
      },
      {
        test: /node_modules[\\/]grpc/,
        use: 'null-loader',
      },
      {
        test: /node_modules[\\/]retry-request/,
        use: 'null-loader',
      },
      {
        test: /node_modules[\\/]https?-proxy-agent/,
        use: 'null-loader',
      },
      {
        test: /node_modules[\\/]gtoken/,
        use: 'null-loader',
      },
    ],
  },
  resolve: {
    alias: {
      '../../../package.json': path.resolve(__dirname, 'package.json'),
    },
    extensions: ['.tsx', '.ts', '.js', '.json'],
  },
  output: {
    filename: 'test',
  },
  plugins: [new ForkTsCheckerWebpackPlugin()],
};
```

**Comment by alexander-fenster** [comment]
Hi @slhck,

```
ERROR in ./node_modules/@grpc/grpc-js/package.json
Module parse failed: Unexpected end of JSON input while parsing near ''
```

This is weird - can you double check this file is not broken for whatever reason? maybe reinstall?

re: PR - I'll take a look, thank you for the contribution and sorry for this taking that long!

**Comment by slhck** [comment]
Sorry for the misunderstanding; the PR was on the third party repo that I used for logging, where I pass the fallback constructor.

The JSON file is simply not there, as it is replaced by the null-loader in `/node_modules[\\/]@grpc[\\/]grpc-js/,` via the webpack config you shared. Hence the error trying to parse it.

**Comment by nicoleczhu** [comment]
@slhck , it sounds like your PR resolved this issue. Feel free to reopen this bug otherwise.
