### ISSUE TITLE
"Maximum call stack size exceeded" on GKE

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-logging#86]
[Originally reported by @dan-j](https://github.com/googleapis/nodejs-logging/issues/53#issuecomment-371390409):

```
(node:40) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:550:31)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
    at replaceProjectIdToken (/home/node/app/node_modules/@google-cloud/common/src/util.js:560:22)
(node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:40) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by stephenplusplus** [comment]
@dan-j 1.1.7 is out with a fix. Sorry for the trouble.

**Comment by Cory-Simon** [comment]
@stephenplusplus npm is only showing 1.1.6 atm

**Comment by stephenplusplus** [comment]
Sorry, I forgot to tag the release through GH. We've been having a lot of issues with CI today, but this one was a human one. I'll post back when it's out.

**Comment by stephenplusplus** [comment]
1.1.7 is out!
